description: |
  Use one of our pre-included templates for sending a success notification when a tagged deployment passes.
  Enter a channel name in the channel parameter to specify which channel to ping.
  Ensure the "space/notify" command is the last command in a job to accurately capture the status.
usage:
  version: 2.1
  orbs:
    space: ark-1/jetbrains-space@1.0.0
    node: circleci/node:4.0
  jobs:
    deploy:
      executor:
        name: node/default
      steps:
        - checkout
        - node/install-packages
        - run:
            command: npm run deploy
        - space/notify:
            event: success
            template: basic_fail_1
            channel: ABCXYZ
  workflows:
    deploy_and_notify:
      jobs:
        - deploy:
            context:
              - jb-space-secrets